spring:
  config:
    activate:
      on-profile: local
  

oneask:
  storage:
    root: "D:/개발 프로그램/OneAsk플랫폼 개발/Backend/buhmwoo-ai-platform/uploads"
  rag:
    backend-url: "http://localhost:8001"

management:
  endpoints:
    web:
      exposure:
        include: "env,configprops"
